OP-Engineering/op-sqlite

- cpp/bridge.cpp
- example/src/tests/queries.spec.ts
When I use COUNT/MAX as column then the app crash on Android. Finally find out sqlite3_column_decltype return NULL    when using sqlite functions.
```js
const db = open({
name: 'test.db',
})
console.log('create table test', db.execute('CREATE TABLE IF NOT EXISTS test (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, age INTEGER NOT NULL);'))
export default function App() {
useEffect(() => {
const query = db.execute('select COUNT(*) from test;')
console.log('query', query)
}, [])
return (
<SafeAreaView className="flex-1 bg-neutral-900">
<View>
<Text>Hello World</Text>
</View>
</SafeAreaView>
);
}
```
When type == NULL, return "UNKNOWN" instead.
> fix: metadata type to 'UNKNOWN' when type is NULL

- README.md
- cpp/bindings.cpp
- cpp/bridge.cpp
- cpp/bridge.h
- example/src/tests/hooks.ts
- src/index.ts
- null guard for sqliteExecute params: `results` and `metadatas`, I accidentally call `SELECT * FROM TABLE` with `executeBatch` it crash, cause null pointer error.
- add methods to remove hooks, so we can implement features like add hook when enter or remove hook when exit.
> Add methods to remove hooks

- android/CMakeLists.txt
Prevents conflicts linking liblog.so
> [ANDROID] Remove native log library

- op-sqlite.podspec
Trying to upgrade to the latest version, I've stumbled on `'create_directories' is unavailable: introduced in iOS 13.0` and `'path' is unavailable: introduced in iOS 13.0` errors in `cpp/utils.cpp`
Bumping deployment targets fixed that. Alternatively, reverting the changes would avoid the bump, but 12.0 is not supported by many libs (Expo, as an example), so seams also like a viable approach
> bumps deployment targets versions

- cpp/bindings.cpp
- cpp/bridge.cpp
- cpp/bridge.h
- example/src/App.tsx
- example/src/tests/dbsetup.spec.ts
- src/index.ts
takes care of #30 
This only enables the API to load an extension. You still need to compile it and place it in a reachable spot (aka a sandbox friendly location in disk) so that sqlite can load into memory. This also means you will have to create a `.so` per OS and possibly contain multiple architectures (ios sim, ios arm sim, ios and for android all the arm versions) so that it gets loaded correctly.
I have not tested such compilation myself yet and would be great if someone can give a hand and test this on their own and confirm it is workin.
> add load extension binding

- README.md
- cpp/bridge.cpp
Loading extensions with the embedded sqlite version is not possible on iOS. This adds a pre-processor macro to avoid compilation errors
> Add warning and conditional compilation of load runtime extensions

- README.md
- cpp/sqlite3.h
SQLite 3.45 brings the JSONB storage format, that allows SQLIte to store and handle its internal JSON implementation in any a blob column to avoid the overhead of parsing JSON text.
More at: https://sqlite.org/releaselog/3_45_1.html
> SQLite upgrade to 3.45.1

- README.md
- android/build.gradle
- cpp/bindings.cpp
- cpp/bridge.cpp
- op-sqlite.podspec
OP_SQLITE_PERF=1 disables thread safety, and the app crashes if used with async parallel methods.
Added OP_SQLITE_PERF=2 (as another optimization profile?) to support the other optimization flags and keep thread safety (via serialized mode).
Some minor fixes on async methods too, rejecting promises in case of SQL Errors instead of throwing errors to keep the a sane behavior.
Late added another fix that prevents the HostObjects to send null values on row properties. All null values (for any type of column) was being converted to zeroes. Fixed.
> OP_SQLITE_PERF=1 crashes with Async Methods

- .gitignore
- android/gradle.properties
Seems I botched the gitignore at some point, ignoring an important configuration file. If the host app does not have kotlin as a dependency it will fail to install.
This re-adds the gradle.properties into the checked repo and fixes https://github.com/OP-Engineering/op-sqlite/issues/56
> Fix missing gradle properties

- cpp/bridge.cpp
Move `sqlite3_reset` call after `sqlite3_step` in `opsqlite_execute_prepared_statement`
Fixes issue where new data does not correctly bind to a prepared statement after the first execution when inserting records, causing an unique constraint exception:
> Error: Exception in HostFunction: [op-sqlite] SQLite code: 19 execution error: UNIQUE constraint failed: mytable.id
Can't share an exact reproduction but the general gist of the issue is doing something like this fails (id is a text primary key):
```typescript
const statement = db.prepareStatement('INSERT INTO mytable (id, name) VALUES (?, ?)');
for (const record of records) {
statement.bind([record.id, record.name]);
statement.execute();
}
``` 
PS Happy to add some tests for this if it looks like a reasonable approach.
> Fix issue where prepared statement can only be used once

- android/CMakeLists.txt
- android/build.gradle
- example/ios/Podfile.lock
- example/package.json
- example/src/tests/queries.spec.ts
- ios/OPSQLite.mm
- op-sqlite.podspec
- package.json
Instead of reading environment variables the configuration now needs to be declared in the package.json:
```
"op-sqlite": {
"sqlcipher": true,
"crsqlite": true,
"performanceMode": "1",
"iosSqlite": false,
"sqliteFlags": "-DSQLITE_DQS=0"
}
```
This lead to more reproducible builds
> New configuration parsing from package.json

- cpp/DBHostObject.cpp
- cpp/DBHostObject.h
Fixes #108. Forgot to reset the flag for the update hook lambda when all the subscribers are cleared.
> Fix de-registration of update hooks

- ios/crsqlite.xcframework/Info.plist
- ios/crsqlite.xcframework/ios-arm64/crsqlite.framework/Info.plist
- ios/crsqlite.xcframework/ios-arm64_x86_64-simulator/crsqlite.framework/Info.plist
Currently there’s an issue submitting an app to the Apple App Store due to a missing version definitions in the cr-sqlite plist files.
For reference, expo-sqlite have experienced the same (see commit https://github.com/expo/expo/commit/de2a96986b29ebc8c71e291a12121e00290e9986)
This PR adds the missing version definitions and allows the app to be submitted to App Store without Apple rejecting the binary.
> fix expo build for cr sql

- ios/libsql.xcframework/Info.plist
Unfortunately, I wasn't able to run the example tests because one of the steps from [the instruction list] (https://ospfranco.notion.site/Libsql-4dbbf5793f654eccb9f5f68901224e97) fails for me:
```
╰──> npx pod-install@latest
Scanning for pods...
1.15.2
> pod install
[!] Invalid `Podfile` file: undefined method `[]' for nil.
>    config = use_native_modules!
Couldn't install Pods. Updating the Pods project and trying again...
> pod install --repo-update
[!] Invalid `Podfile` file: undefined method `[]' for nil.
>    config = use_native_modules!
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: undefined method `[]' for nil.
>    config = use_native_modules!
pod install --repo-update --ansi exited with …
```
> Update Libsql libraries

- cpp/DBHostObject.cpp
- cpp/DBHostObject.h
- cpp/bindings.cpp
- cpp/bridge.cpp
- example/ios/Podfile.lock
- example/src/App.tsx
- example/src/Database.ts
Should take care of
https://github.com/OP-Engineering/op-sqlite/issues/154
> Invalidate HostObjects on module hot reload

- cpp/DBHostObject.cpp
- cpp/DBHostObject.h
- example/ios/Podfile.lock
- example/package.json
- example/src/tests/dbsetup.spec.ts
- example/src/tests/hooks.spec.ts
- example/src/tests/queries.spec.ts
- example/src/tests/reactive.spec.ts
- src/index.ts
- turbo.json
> Fix reactive queries by triggering them only on transactions after commit

- android/build.gradle
I was testing the newly released 9.2.5 with RN 0.76 (thanks for adding the prompt support) but ran into a build error on android:
```
Execution failed for task ':app:mergeReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
> 2 files found with path 'lib/arm64-v8a/libreactnative.so' from inputs:
```
This submitted diff appeared to resolve the issue for me.
> exclude libreactnative.so

- cpp/DBHostObject.cpp
- example/ios/Podfile.lock
- example/src/tests/reactive.spec.ts
Fixes https://github.com/OP-Engineering/op-sqlite/issues/177
> Clear pending reactive queries after firing

- android/build.gradle
- example/ios/Podfile.lock
- example/package.json
- lefthook.yml
- op-sqlite.podspec
People do not read the manual and also are too abstracted away from the C++ threads to understand was going on. Changing it to have only the thread safe flags enabled to avoid confusing and having to close the same tickets over and over again.
> Turn performance mode into a single boolean

- cpp/libsql/libsql.h
- ios/libsql.xcframework/ios-arm64/Headers/libsql.h
- ios/libsql.xcframework/ios-arm64_x86_64-simulator/Headers/libsql.h
It includes some fixes to vector search.
> Update libsql to 3d52c07f5d1df9caa56fb201fb3009924b26fd05

- android/src/main/java/com/op/sqlite/OPSQLiteModule.kt
- cpp/bridge.cpp
- example/ios/OPSQLiteExample.xcodeproj/project.pbxproj
- example/src/App.tsx
- ios/OPSQLite.mm
- src/index.ts
It's now possible to load dylibs on iOS to call the sqlite method to load an extension. This was always possible on Android but on iOS dylibs are heavily restricted and packaged into frameworks, this requires to get the runtime path of the packaged binary from iOS APIs. There is now a method one can use to get the binary path on iOS and pass the full path to the loadExtension call to sqlite.
Docs are updated, scroll down to loading extensions:
https://ospfranco.notion.site/API-1a39b6bb3eb74eb893d640c8c3459362
> Add getDylibPath for loading runtime extensions on iOS

- c_sources/tokenizers.h
- cpp/DBHostObject.h
- cpp/PreparedStatementHostObject.cpp
- cpp/bridge.cpp
- cpp/bridge.h
- example/c_sources/tokenizers.h
- example/ios/Podfile.lock
- example/package.json
- generate_tokenizers_header_file.rb
- op-sqlite.podspec
It should help getting the package to run next to expo-updates
> Fix compilation for system sqlite on iOS

- docs/docusaurus.config.ts
> fix: github url typo

- ios/sqlitevec.xcframework/ios-arm64/sqlitevec.framework/Info.plist
- ios/sqlitevec.xcframework/ios-arm64_x86_64-simulator/sqlitevec.framework/Info.plist
It was missed in #216.
I got the version mismatched error on upload app to TestFlight, and confirmed it can be fixed by this PR.
> Fix MinimumOSVersion in sqlitevec.xcframework

- cpp/bindings.cpp
- cpp/bridge.cpp
- cpp/libsql/bridge.cpp
- example/src/tests/dbsetup.spec.ts
> Do not use realpath to resolve location

- cpp/bindings.cpp
- cpp/bindings.h
- docs/docs/installation.md
- example/ios/OPSQLiteExample/AppDelegate.mm
- ios/OPSQLite.h
- ios/OPSQLite.mm
Fixes #214.
A new function is added in the iOS bindings:
You should call it from AppDelegate in the `didFinishLaunchingWithOptions` call before calling super and expo-updates tries to open a database:
> Add new expoUpdatesWorkaround function to avoid expo-updates crashing

- README.md
- docs/docs/ORM_Libs.md
- src/index.ts
Drizzle did not pin their dependency to an specific version, so it tries to pull the latest versions of op-sqlite which have a slightly different API and it breaks.
This re-adds the old function name so things start working again and people stop complaining about it to me.
Fixes https://github.com/drizzle-team/drizzle-orm/issues/3002 and makes https://github.com/drizzle-team/drizzle-orm/pull/3727 redundant.
> Re add executeRawAsync function

- src/Storage.ts
I've tried to use the KV Storage class from op-sqlite but got the error `[TypeError: 0, _.open is not a function (it is undefined)]` on android (weirdly enough it works on ios).
I've fixed the error by changing the import in Storage.ts from:
```ts
import { open, type DB } from '.';
```
to
```ts
import { open, type DB } from './index';
```
> fix: open function is undefined

- docs/docs/installation.md
I made an Expo plugin to continue to support the Expo CNG for those that use `use_frameworks` and want `op-sqlite` to be built static.
> Adding CNG support for expo use_frameworks folks to docs

- op-sqlite.podspec
`File.expand_path` properly resolves symlinks, so this should fix #172 
I tested this in both a monorepo project with symlinked node_modules, and also a non-monorepo project.
Let me know if you have any concerns.
> fix podspec file to resolve symlinks to find package.json

- op-sqlite.podspec
- package.json
Closes #172 and #264
Based on #259
> Resolution for monorepos

- docs/docs/installation.md
This pull request updates the installation documentation for the `op-sqlite` package to include important guidance for users working in monorepo environments.
Documentation improvements:
* [`docs/docs/installation.md`](diffhunk://#diff-19fd876fb56da88a1becb80817b52db1a40e8491641d547913b93bb7ecda3d22R27-R32): Added a note explaining that when using a monorepo, the "op-sqlite" configuration must be added to the root `package.json` file. The note also provides an alternative solution to prevent the package from being hoisted to the root `node_modules` and suggests checking the `ios/Podfile.lock` file for installation details.
> monorepo warning

- example/src/tests/queries.spec.ts
- src/index.ts
Fixes #270 by recursively sanitizing any param array
> Sanitizes the passed params (looking for array buffers) recursively

- cpp/DBHostObject.cpp
- cpp/DBHostObject.h
- cpp/bindings.cpp
- cpp/libsql/bridge.cpp
- cpp/libsql/bridge.h
- example/ios/Podfile.lock
- example/package.json
- example/src/tests/storage.spec.ts
- src/index.ts
renamed the `syncInterval` param to `libsqlSyncInterval` and add a new `libsqlOffline` param to the `openSync` call
> Expose offline flag for libsql

- cpp/DBHostObject.cpp
- cpp/DBHostObject.h
- cpp/bindings.cpp
- cpp/libsql/bridge.cpp
- cpp/libsql/bridge.h
- docs/docs/Libsql/start.md
- example/ios/Podfile.lock
- example/package.json
- example/src/App.tsx
- example/src/tests/queries.spec.ts
- src/index.ts
In theory this enables encryption on libsql. I tried opening the local file with tableplus (providing the same passphrase) but all I get is an error, so I've personally not been able to verify encryption is working. Running a query all I get is `Query 1 ERROR at Line 1: : SQL logic error`.
At least [this comment](https://github.com/OP-Engineering/op-sqlite/pull/286#issuecomment-2968524655) by the Turso team says that's all that is needed.
Docs have been updated as well. The `openSync` call now supports an `encryptionKey` param that will pass this to the libsql config when opening the sync connection.
Closes #224
> Add new param to libsql openSync, encryptionKey, which enables encryption

- c_sources/tokenizers.h
- cpp/DBHostObject.h
- cpp/PreparedStatementHostObject.h
- cpp/bridge.h
- cpp/utils.h
- example/c_sources/tokenizers.h
Thought it was wroking, but sadly came across the build issues on android again where it expects "" instead of <> , guess I didn't correctly clear the cache before testing the changes: 
```
error: 'sqlite3.h' file not found with <angled> include; use "quotes" instead
7 | #include <sqlite3.h>
|          ^
2 errors generated.
```
As you stated earlier its needed to keep diamond brackets for iOS, so to fix it we can just use the macro which checks if android :
```
#ifdef __ANDROID__
#include "sqlite3.h"
#else
#include <sqlite3.h>
#endif
```
> Fixes the issue I initially faced on android with prefab publishing

- android/build.gradle
Unifies the behavior of going up the directories to find the op-sqlite configuration in the smallest common denominator folder. Useful for Monorepo builds. Closes #294
> Traverse directories on Android upwards to find op-sqlite

- .github/workflows/ci.yml
Unblocks CI due to github update of their macOS runners. Unblocks #312
> Try selecting xcode versions for CI

- cpp/libsql/bridge.cpp
- ios/libsql.xcframework/Info.plist
- Update the libsql libraries
- Prevent sending a empty remote encryption key, the libsql binding code will check if `remote_encryption_key` is empty before trying to set a encryption key.
> Prevent sending empty remote encryption key
